package LNProyecto;

public class ClsConstantes 
{
	public static enum enFicDatos 
	{ 
		FICHERO_DATOS_SUGERENCIA, FICHERO_DATOS_CONTRASENA, FICHERO_DATOS_NUMERADOR, FICHERO_DATOS_BLOQUEO, FICHERO_DATOS_ARTICULOS, FICHERO_DATOS_QUEJA, FICHERO_DATOS_COMENTARIOS
	}
}
